/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        parchment: "#121214",
        parchmentLift: "#151518",
        vellum: "#1A1A1E",
        glass: "rgba(24,24,27,0.94)",
        ink: "#F4F4F5",
        inkMuted: "#A1A1AA",
        inkFaint: "rgba(244,244,245,0.62)",
        hairline: "rgba(255,255,255,0.07)",
        hairlineStrong: "rgba(255,255,255,0.14)",
        mineral: "#242429",
        mineralDark: "#71717A",
        gold: "#7C8CFF",
        goldSoft: "#24283A",
        olive: "#7C8CFF",
        oliveSoft: "#24283A",
        blue: "#7C8CFF",
        blueSoft: "#24283A",
        rose: "#7C8CFF",
        roseSoft: "#24283A",
        danger: "#E06C75",
        shadow: "rgba(0,0,0,0.44)",
        white: "#FFFFFF",
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        card: "hsl(var(--card) / <alpha-value>)",
        "card-foreground": "hsl(var(--card-foreground) / <alpha-value>)",
        popover: "hsl(var(--popover) / <alpha-value>)",
        "popover-foreground": "hsl(var(--popover-foreground) / <alpha-value>)",
        primary: "hsl(var(--primary) / <alpha-value>)",
        "primary-foreground": "hsl(var(--primary-foreground) / <alpha-value>)",
        secondary: "hsl(var(--secondary) / <alpha-value>)",
        "secondary-foreground":
          "hsl(var(--secondary-foreground) / <alpha-value>)",
        muted: "hsl(var(--muted) / <alpha-value>)",
        "muted-foreground": "hsl(var(--muted-foreground) / <alpha-value>)",
        accent: "hsl(var(--accent) / <alpha-value>)",
        "accent-foreground": "hsl(var(--accent-foreground) / <alpha-value>)",
        destructive: "hsl(var(--destructive) / <alpha-value>)",
        "destructive-foreground":
          "hsl(var(--destructive-foreground) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        ring: "hsl(var(--ring) / <alpha-value>)",
      },
      borderRadius: { sm: "10px", md: "18px", lg: "26px", xl: "32px" },
      fontFamily: {
        sans: ["Manrope_400Regular"],
        body: ["Manrope_400Regular"],
        label: ["Manrope_500Medium"],
        heading: ["Manrope_600SemiBold"],
        strong: ["Manrope_700Bold"],
        hebrew: ["NotoSansHebrew_400Regular"],
        "hebrew-heading": ["NotoSansHebrew_600SemiBold"],
      },
      boxShadow: {
        card: "0 1px 2px rgba(0,0,0,0.4)",
        floating: "0 12px 32px rgba(0,0,0,0.34)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
