/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        parchment: "#F5F7FA",
        parchmentLift: "#FAFCFF",
        vellum: "#FFFFFF",
        glass: "rgba(255,255,255,0.88)",
        ink: "#202936",
        inkMuted: "#647082",
        inkFaint: "rgba(15,15,20,0.62)",
        hairline: "rgba(11,26,59,0.07)",
        hairlineStrong: "rgba(11,26,59,0.16)",
        mineral: "#EDF1F6",
        mineralDark: "#7D8999",
        gold: "#285EA8",
        goldSoft: "#E6EFFA",
        olive: "#285EA8",
        oliveSoft: "#E6EFFA",
        blue: "#285EA8",
        blueSoft: "#E6EFFA",
        rose: "#285EA8",
        roseSoft: "#E6EFFA",
        danger: "#B44343",
        shadow: "rgba(17, 20, 18, 0.11)",
        white: "#FFFFFF",
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        card: "hsl(var(--card) / <alpha-value>)",
        "card-foreground": "hsl(var(--card-foreground) / <alpha-value>)",
        popover: "hsl(var(--popover) / <alpha-value>)",
        "popover-foreground": "hsl(var(--popover-foreground) / <alpha-value>)",
        primary: "hsl(var(--primary) / <alpha-value>)",
        "primary-foreground": "hsl(var(--primary-foreground) / <alpha-value>)",
        secondary: "hsl(var(--secondary) / <alpha-value>)",
        "secondary-foreground":
          "hsl(var(--secondary-foreground) / <alpha-value>)",
        muted: "hsl(var(--muted) / <alpha-value>)",
        "muted-foreground": "hsl(var(--muted-foreground) / <alpha-value>)",
        accent: "hsl(var(--accent) / <alpha-value>)",
        "accent-foreground": "hsl(var(--accent-foreground) / <alpha-value>)",
        destructive: "hsl(var(--destructive) / <alpha-value>)",
        "destructive-foreground":
          "hsl(var(--destructive-foreground) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        ring: "hsl(var(--ring) / <alpha-value>)",
      },
      borderRadius: { sm: "10px", md: "18px", lg: "26px", xl: "32px" },
      fontFamily: {
        sans: ["Manrope_400Regular"],
        body: ["Manrope_400Regular"],
        label: ["Manrope_500Medium"],
        heading: ["Manrope_600SemiBold"],
        strong: ["Manrope_700Bold"],
        hebrew: ["NotoSansHebrew_400Regular"],
        "hebrew-heading": ["NotoSansHebrew_600SemiBold"],
      },
      boxShadow: {
        card: "0 4px 20px rgba(35,63,100,0.035)",
        floating: "0 4px 16px rgba(11,26,59,0.06)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
