/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        parchment: "var(--parchment)",
        parchmentLift: "var(--parchmentLift)",
        vellum: "var(--vellum)",
        glass: "var(--glass)",
        ink: "var(--ink)",
        inkMuted: "var(--inkMuted)",
        inkFaint: "var(--inkFaint)",
        hairline: "var(--hairline)",
        hairlineStrong: "var(--hairlineStrong)",
        mineral: "var(--mineral)",
        mineralDark: "var(--mineralDark)",
        gold: "var(--gold)",
        goldSoft: "var(--goldSoft)",
        olive: "var(--olive)",
        oliveSoft: "var(--oliveSoft)",
        blue: "var(--blue)",
        blueSoft: "var(--blueSoft)",
        rose: "var(--rose)",
        roseSoft: "var(--roseSoft)",
        danger: "var(--danger)",
        shadow: "var(--shadow)",
        white: "var(--white)",
        onAccent: "var(--onAccent)",
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        card: "hsl(var(--card) / <alpha-value>)",
        "card-foreground": "hsl(var(--card-foreground) / <alpha-value>)",
        popover: "hsl(var(--popover) / <alpha-value>)",
        "popover-foreground": "hsl(var(--popover-foreground) / <alpha-value>)",
        primary: "hsl(var(--primary) / <alpha-value>)",
        "primary-foreground": "hsl(var(--primary-foreground) / <alpha-value>)",
        secondary: "hsl(var(--secondary) / <alpha-value>)",
        "secondary-foreground":
          "hsl(var(--secondary-foreground) / <alpha-value>)",
        muted: "hsl(var(--muted) / <alpha-value>)",
        "muted-foreground": "hsl(var(--muted-foreground) / <alpha-value>)",
        accent: "hsl(var(--accent) / <alpha-value>)",
        "accent-foreground": "hsl(var(--accent-foreground) / <alpha-value>)",
        destructive: "hsl(var(--destructive) / <alpha-value>)",
        "destructive-foreground":
          "hsl(var(--destructive-foreground) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        ring: "hsl(var(--ring) / <alpha-value>)",
      },
      borderRadius: { sm: "10px", md: "18px", lg: "26px", xl: "32px" },
      fontFamily: {
        sans: ["Manrope_400Regular"],
        body: ["Manrope_400Regular"],
        label: ["Manrope_500Medium"],
        heading: ["Manrope_600SemiBold"],
        strong: ["Manrope_700Bold"],
        hebrew: ["NotoSansHebrew_400Regular"],
        "hebrew-heading": ["NotoSansHebrew_600SemiBold"],
      },
      boxShadow: {
        card: "0 1px 2px rgba(0,0,0,0.4)",
        floating: "0 12px 32px rgba(0,0,0,0.34)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
