"""Build and Apple-sign the distributable shortcut on macOS; no user data embedded."""
import base64, json, pathlib, plistlib, subprocess, tempfile
root = pathlib.Path(__file__).resolve().parents[2]
source = root / 'assets/shortcuts/PrayerFocus.json'
output = root / 'assets/shortcuts/Kavanah Prayer Focus.shortcut'
with tempfile.TemporaryDirectory() as directory:
    unsigned = pathlib.Path(directory) / 'PrayerFocus.shortcut'
    unsigned.write_bytes(plistlib.dumps(json.loads(source.read_text())))
    signed = pathlib.Path(directory) / 'Signed.shortcut'
    subprocess.run(['shortcuts', 'sign', '--mode', 'anyone', '--input', str(unsigned), '--output', str(signed)], check=True)
    if not signed.exists() or signed.stat().st_size < 1000:
        raise RuntimeError('Apple signing did not produce an artifact. Do not ship an unsigned shortcut.')
    output.write_bytes(signed.read_bytes())
encoded = base64.b64encode(output.read_bytes()).decode()
(root / 'src/data/shortcuts/prayerFocus.ts').write_text('// Generated by scripts/shortcuts/build.py. Apple-signed, public shortcut; no personal data.\nexport const prayerFocusShortcutBase64 = ' + json.dumps(encoded) + ';\n')
