import { writeFileSync } from "node:fs";
import { corePrayers } from "../../src/data/corePrayers";
const q = (s: string) => `'${s.replaceAll("'", "''")}'`;
const catalog = corePrayers;
const rows = catalog.map((p) => `(${q(p.id)},${q(p.title)},${q(p.category)},true)`);
const passages = corePrayers.flatMap((p) =>
  p.tokens.flatMap((t, i) =>
    [
      ["he", t.hebrew],
      ["en", t.translation],
      ["transliteration", t.transliteration],
    ]
      .filter(([, text]) => text?.trim())
      .map(
        ([lang, text]) =>
          `(${q(`${p.id}:${i}:${lang}`)},${q(p.id)},${q(lang!)},${q(text!)},${q(p.sefariaRef)})`,
      ),
  ),
);
writeFileSync(
  "supabase/migrations/202609270001_research_catalog.sql",
  `-- Generated by backend:catalog from the research snapshot. Expert review remains pending.
begin;
alter table private.catalog add column if not exists active boolean not null default false;
update private.catalog set active=false;
insert into private.catalog(id,title,practice,active) values
${rows.join(",\n")} on conflict(id) do update set title=excluded.title,practice=excluded.practice,active=true;
-- Preserve historical catalog identities and user sessions; replace only the quotable text pool.
delete from private.passages;
insert into private.passages(id,prayer_id,language,body,source_ref) values
${passages.join(",\n")};
create or replace function private.require_active_prayer() returns trigger
language plpgsql security definer set search_path='' as $$
begin
 if not exists(select 1 from private.catalog where id=new.prayer_id and active) then
  raise exception 'This prayer is not in the current research catalog.';
 end if;
 return new;
end $$;
revoke all on function private.require_active_prayer() from public;
drop trigger if exists active_prayer on private.sessions;
create trigger active_prayer before insert on private.sessions for each row execute function private.require_active_prayer();
drop trigger if exists active_prayer on public.circle_activity;
create trigger active_prayer before insert or update on public.circle_activity for each row execute function private.require_active_prayer();
commit;
`,
);
